
const SERVICES=[
{id:'pothole',title:'Potholes & street repair',icon:'🛣️',category:'roads',keywords:'pothole pavement road street damage debris',agency:'LA County Public Works',division:'Road Maintenance Division',description:'Report damaged pavement, roadway debris, and unsafe street conditions.',prepare:'Exact location, direction of travel, approximate size, and a photo.'},
{id:'speeding',title:'Speeding & traffic calming',icon:'🚗',category:'roads',keywords:'speeding speed bump hump traffic stop sign crosswalk',agency:'LA County Public Works',division:'Traffic & Lighting Division',description:'Request traffic studies, signage, or consideration of traffic-calming measures.',prepare:'Street segment, times, observed behavior, requested measure, and community support.'},
{id:'graffiti',title:'Graffiti removal',icon:'🎨',category:'community',keywords:'graffiti vandalism paint wall cleanup',agency:'LA County Public Works',division:'Graffiti Abatement',description:'Route graffiti reports to the appropriate cleanup program.',prepare:'Photo, exact location, surface type, and whether offensive content is present.'},
{id:'dumping',title:'Illegal dumping',icon:'🗑️',category:'community',keywords:'dumping trash furniture waste bulky items',agency:'LA County Public Works',division:'Environmental Programs Division',description:'Report abandoned furniture, dumped waste, or debris in public areas.',prepare:'Material type, size, location, and whether it blocks travel.'},
{id:'housing',title:'Rent & housing help',icon:'🏠',category:'housing',keywords:'rent tenant landlord eviction housing homelessness repairs',agency:'LA County Department of Consumer and Business Affairs',division:'Housing and Tenant Protections',description:'Find tenant resources, rental assistance, mediation, and housing support.',prepare:'Address, tenancy status, notices received, and the type of help needed.'},
{id:'sheriff',title:'Non-emergency public safety',icon:'🛡️',category:'safety',keywords:'sheriff crime suspicious patrol safety non emergency',agency:'Los Angeles County Sheriff’s Department',division:'Walnut/Diamond Bar Station',description:'Find the correct contact for non-emergency safety concerns.',prepare:'Location, time, factual description, and identifying details if safely observed.'},
{id:'schools',title:'Schools & youth services',icon:'🎓',category:'community',keywords:'school student youth education bus bullying district',agency:'Rowland Unified School District',division:'District and School-Site Services',description:'Connect with school, student support, transportation, and youth resources.',prepare:'School name, student grade if relevant, and the type of support needed.'},
{id:'utilities',title:'Utilities & outages',icon:'💡',category:'utilities',keywords:'power outage gas water utility streetlight electricity',agency:'Relevant Utility Provider',division:'Customer and Emergency Services',description:'Find the provider responsible for power, gas, water, or streetlight concerns.',prepare:'Service address, provider, outage type, and whether there is an immediate hazard.'},
{id:'code',title:'Property & code concerns',icon:'🏗️',category:'community',keywords:'code enforcement building unsafe zoning weeds property',agency:'LA County Public Works',division:'Building and Safety / Code Enforcement',description:'Report observable property maintenance, zoning, or building-safety concerns.',prepare:'Property address and a factual description visible from public property.'}
];
const AGENCIES=[
{name:'LA County Public Works',topic:'roads',icon:'🏗️',handles:['Road maintenance','Traffic and lighting','Building and safety','Graffiti','Illegal dumping'],description:'Handles infrastructure, road, traffic, environmental, and building concerns in unincorporated Rowland Heights.'},
{name:'Los Angeles County Sheriff’s Department',topic:'safety',icon:'🛡️',handles:['Non-emergency calls','Patrol services','Crime reports','Community safety'],description:'Provides law-enforcement services through the Walnut/Diamond Bar Station.'},
{name:'Rowland Unified School District',topic:'community',icon:'🎓',handles:['Schools','Student services','Transportation','Family resources'],description:'Provides K–12 education and district services for local students and families.'},
{name:'LA County Department of Consumer and Business Affairs',topic:'housing',icon:'🏠',handles:['Tenant protections','Mediation','Consumer help','Small-business resources'],description:'Provides consumer, tenant, and business assistance.'},
{name:'211 LA',topic:'community',icon:'☎️',handles:['Food assistance','Shelter','Health resources','Family support'],description:'Connects residents with social services and nonprofit assistance throughout Los Angeles County.'},
{name:'Utility Providers',topic:'utilities',icon:'💡',handles:['Power','Gas','Water','Outages','Service emergencies'],description:'The responsible provider depends on the address and type of utility service.'}
];
const REPORT_TYPES={
speeding:{label:'Speeding or traffic-calming request',agency:'LA County Public Works — Traffic & Lighting Division',questions:[['streetSegment','Street segment involved','Example: Fullerton Road between Colima and Pathfinder'],['problemTimes','When does the problem usually occur?','Morning commute, weekends, after school'],['requestedMeasure','What improvement are you requesting?','Traffic study, speed feedback sign, speed hump consideration'],['support','Have neighbors expressed support?','Describe signatures, conversations, or known concerns']]},
pothole:{label:'Pothole or road damage',agency:'LA County Public Works — Road Maintenance Division',questions:[['lane','Where in the roadway is it?','Lane, shoulder, direction of travel'],['size','Approximate size and severity','Width, depth, or immediate hazard']]},
graffiti:{label:'Graffiti',agency:'LA County Public Works — Graffiti Abatement',questions:[['surface','What surface is affected?','Wall, sign, utility box, bridge'],['offensive','Is the content threatening or offensive?','Describe without repeating slurs']]},
dumping:{label:'Illegal dumping',agency:'LA County Public Works — Environmental Programs',questions:[['material','What material was dumped?','Furniture, construction debris, household waste'],['blocking','Does it block a road or walkway?','Describe any immediate hazard']]},
housing:{label:'Housing or tenant concern',agency:'LA County Department of Consumer and Business Affairs',questions:[['housingIssue','What type of housing issue is this?','Rent increase, eviction notice, repairs, discrimination'],['deadline','Is there an upcoming deadline?','Notice date, hearing date, or required response']]},
safety:{label:'Non-emergency safety concern',agency:'Los Angeles County Sheriff’s Department',questions:[['timeObserved','When did this occur?','Date and approximate time'],['descriptionObserved','What did you observe?','Factual details only; do not place yourself at risk']]},
school:{label:'School or youth-service concern',agency:'Rowland Unified School District',questions:[['schoolName','Which school or program?','School name or district program'],['studentNeed','What help is needed?','Transportation, student services, enrollment, safety']]},
other:{label:'Other or not sure',agency:'RHCCC navigation assistance',questions:[['desiredOutcome','What outcome are you seeking?','Explain what you would like to happen']]}
};
const EVENTS=[
{type:'meeting',date:'AUG 10',time:'6:30 PM',title:'RHCCC General Meeting',location:'Rowland Heights Community Center',description:'Community updates, guest speakers, public comment, and local service information.'},
{type:'volunteer',date:'AUG 17',time:'10:00 AM',title:'Neighborhood Cleanup',location:'Location to be announced',description:'Volunteer litter removal, neighborhood observation, and beautification.'},
{type:'workshop',date:'AUG 24',time:'7:00 PM',title:'Public Safety Workshop',location:'Rowland Heights',description:'Learn how to report non-emergency concerns and meet local representatives.'}
];
